-- Migration: Create all tables for the job-info BFF service
-- Run order: 001

-- JOBS table: core job record with status badges stored as a JSONB array
CREATE TABLE IF NOT EXISTS "JOBS" (
    "ID"            BIGSERIAL       PRIMARY KEY,
    "JOB_ID"        VARCHAR(100)    NOT NULL,
    "STATUS_BADGES" JSONB           NOT NULL DEFAULT '[]',
    "CREATED_AT"    TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"    TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_jobs_job_id UNIQUE ("JOB_ID")
);

CREATE INDEX IF NOT EXISTS idx_jobs_job_id ON "JOBS" ("JOB_ID");

-- GENERAL_INFO table: one-to-one with JOBS (branch, dates, prices)
CREATE TABLE IF NOT EXISTS "GENERAL_INFO" (
    "ID"                       BIGSERIAL       PRIMARY KEY,
    "JOB_ID"                   VARCHAR(100)    NOT NULL,
    "BRANCH"                   VARCHAR(200),
    "LOAN_CONTRACT_DATE"       VARCHAR(50),
    "SPOUSE_CONSENT_DATE"      VARCHAR(50),
    "GUARANTEE_CONTRACT_DATE"  VARCHAR(50),
    "MORTGAGE_DATE"            VARCHAR(50),
    "APPRAISAL_PRICE"          NUMERIC(18,2),
    "SALE_PRICE"               NUMERIC(18,2),
    "CREATED_AT"               TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"               TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_general_info_job_id UNIQUE ("JOB_ID"),
    CONSTRAINT fk_general_info_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_general_info_job_id ON "GENERAL_INFO" ("JOB_ID");

-- CFA_INFO table: one-to-one with JOBS (credit facility amendment info)
CREATE TABLE IF NOT EXISTS "CFA_INFO" (
    "ID"                BIGSERIAL       PRIMARY KEY,
    "JOB_ID"            VARCHAR(100)    NOT NULL,
    "TOTAL_CREDIT_OLD"  NUMERIC(18,2),
    "TOTAL_CREDIT_NEW"  NUMERIC(18,2),
    "CREDIT_CHANGE"     NUMERIC(18,2),
    "CFA_OLD_DATE"      VARCHAR(50),
    "CFA_CURRENT_ROUND" INTEGER,
    "DEBT_PERIOD_OLD"   INTEGER,
    "DEBT_PERIOD_NEW"   INTEGER,
    "CREATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cfa_info_job_id UNIQUE ("JOB_ID"),
    CONSTRAINT fk_cfa_info_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cfa_info_job_id ON "CFA_INFO" ("JOB_ID");

-- LOAN_APPLICANTS table: one-to-many with JOBS
CREATE TABLE IF NOT EXISTS "LOAN_APPLICANTS" (
    "ID"                BIGSERIAL       PRIMARY KEY,
    "JOB_ID"            VARCHAR(100)    NOT NULL,
    "FULL_NAME"         VARCHAR(200)    NOT NULL,
    "NATIONAL_ID"       VARCHAR(50),
    "AGE"               INTEGER,
    "NATIONALITY"       VARCHAR(100),
    "PARENTS"           VARCHAR(200),
    "MARITAL_STATUS"    VARCHAR(50),
    "BORROWER_TYPE"     VARCHAR(100),
    "COLLATERAL_OWNER"  BOOLEAN         NOT NULL DEFAULT FALSE,
    "CREATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_loan_applicants_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_loan_applicants_job_id ON "LOAN_APPLICANTS" ("JOB_ID");

-- LOAN_DETAILS table: one-to-many with JOBS
CREATE TABLE IF NOT EXISTS "LOAN_DETAILS" (
    "ID"                  BIGSERIAL       PRIMARY KEY,
    "JOB_ID"              VARCHAR(100)    NOT NULL,
    "LOAN_TYPE"           VARCHAR(100),
    "LOAN_AMOUNT"         NUMERIC(18,2),
    "INTEREST_RATE"       NUMERIC(8,4),
    "LOAN_PERIOD"         INTEGER,
    "INSTALLMENT_AMOUNT"  NUMERIC(18,2),
    "CREATED_AT"          TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"          TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_loan_details_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_loan_details_job_id ON "LOAN_DETAILS" ("JOB_ID");

-- COLLATERALS table: one-to-many with JOBS
CREATE TABLE IF NOT EXISTS "COLLATERALS" (
    "ID"                BIGSERIAL       PRIMARY KEY,
    "JOB_ID"            VARCHAR(100)    NOT NULL,
    "COLLATERAL_ID"     VARCHAR(100)    NOT NULL,
    "COLLATERAL_TYPE"   VARCHAR(100),
    "TITLE_DEED_NUMBER" VARCHAR(100),
    "LAND_AREA"         NUMERIC(18,4),
    "APPRAISAL_PRICE"   NUMERIC(18,2),
    "LOCATION"          TEXT,
    "CREATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"        TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_collaterals_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_collaterals_job_id ON "COLLATERALS" ("JOB_ID");

-- CONTRACTS table: one-to-many with JOBS; document_links stored as JSONB array
CREATE TABLE IF NOT EXISTS "CONTRACTS" (
    "ID"              BIGSERIAL       PRIMARY KEY,
    "JOB_ID"          VARCHAR(100)    NOT NULL,
    "CONTRACT_ID"     VARCHAR(100)    NOT NULL,
    "CONTRACT_TYPE"   VARCHAR(100),
    "CREDIT_LIMIT"    NUMERIC(18,2),
    "BORROWER_NAME"   VARCHAR(200),
    "REVIEW_STATUS"   VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    "DOCUMENT_LINKS"  JSONB           NOT NULL DEFAULT '[]',
    "CREATED_AT"      TIMESTAMP       NOT NULL DEFAULT NOW(),
    "UPDATED_AT"      TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_contracts_job_contract UNIQUE ("JOB_ID", "CONTRACT_ID"),
    CONSTRAINT fk_contracts_job_id FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contracts_job_id ON "CONTRACTS" ("JOB_ID");

-- Seed data for local development
INSERT INTO "JOBS" ("JOB_ID", "STATUS_BADGES")
VALUES ('JOB-2024-001', '["PENDING_REVIEW","DOCUMENTS_REQUIRED"]')
ON CONFLICT ("JOB_ID") DO NOTHING;

INSERT INTO "GENERAL_INFO" ("JOB_ID", "BRANCH", "APPRAISAL_PRICE", "SALE_PRICE")
VALUES ('JOB-2024-001', 'Head Office', 5000000.00, 4800000.00)
ON CONFLICT ("JOB_ID") DO NOTHING;

INSERT INTO "CFA_INFO" ("JOB_ID", "TOTAL_CREDIT_OLD", "TOTAL_CREDIT_NEW", "CREDIT_CHANGE", "CFA_CURRENT_ROUND")
VALUES ('JOB-2024-001', 2000000.00, 3000000.00, 1000000.00, 2)
ON CONFLICT ("JOB_ID") DO NOTHING;

INSERT INTO "LOAN_APPLICANTS" ("JOB_ID", "FULL_NAME", "NATIONAL_ID", "AGE", "BORROWER_TYPE", "COLLATERAL_OWNER")
VALUES ('JOB-2024-001', 'Somchai Jaidee', '1234567890123', 42, 'PRIMARY', TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO "CONTRACTS" ("JOB_ID", "CONTRACT_ID", "CONTRACT_TYPE", "CREDIT_LIMIT", "BORROWER_NAME", "REVIEW_STATUS", "DOCUMENT_LINKS")
VALUES ('JOB-2024-001', 'CNT-001', 'MORTGAGE', 4500000.00, 'Somchai Jaidee', 'PENDING', '["https://storage.example.com/docs/cnt-001.pdf"]')
ON CONFLICT ("JOB_ID", "CONTRACT_ID") DO NOTHING;
